### ISSUE TITLE
Include a mode to make Ractive use dashed variable names 

### ISSUE THREAD

**Issue by ceremcem** [ractivejs/ractive#2587]
**Enhancement**

We use Ractive heavily with Livescript. When we define a variable in Livescript, the preferred naming convention is dashed style, like so: 

```
my-variable = 3
my-other-variable = new X
```

If we define a ractive instance in the same way, `data: {}` dictionary has keys that are named similarly: 

```
ractive = new Ractive do 
    el: "#aa"
    template: "#bb"
    data: 
        my-var: 3
        my-other-var: 
```

From this point, I have to use `ractive.get()` and `ractive.set()` by manually capitalizing the dashed names, even in Livescript: 

```
x = ractive.get "myVar"
ractive.set "myOtherVar", x
```

If we could set Ractive mode, like `Ractive.mode = "livescript"` and use `.set`, `.get` functions with `dashed-names`, it would be great: 

```
x = ractive.get "my-var"
ractive.set "my-other-var", x
```
