### ISSUE TITLE
CSS @import corrupts scoped CSS

### ISSUE THREAD

**Issue by p3k** [ractivejs/ractive#3254]
## Description:

Assume the following example:

```js
const css = `
  body { background-color: red; }
  .foo { color: green; }
`;

const template = `
  <div class='foo'>Hello, World!</div>
`;

const App = Ractive.extend({
  css,
  template
});

Ractive({
  components: { App },
  target: '#app',
  template: '<App/>'
});
```

This renders a green text on a default background and correctly scopes the styles, no issue here:

```css
/* Ractive.js component styles */

/* {6dc0437c-13f6-1d65-b647-481773bded6a} */

  body[data-ractive-css~="{6dc0437c-13f6-1d65-b647-481773bded6a}"], [data-ractive-css~="{6dc0437c-13f6-1d65-b647-481773bded6a}"] body { background-color: red; }
  .foo[data-ractive-css~="{6dc0437c-13f6-1d65-b647-481773bded6a}"], [data-ractive-css~="{6dc0437c-13f6-1d65-b647-481773bded6a}"] .foo { color: green; }
```

However, when I add a CSS `@import` directive, e.g. for loading a font, the rendered CSS for `body` suddenly becomes unscoped and thus, the background appears red:

```js
const css = `
  @import url('https://fonts.googleapis.com/css?family=Shrikhand');
  body { background-color: red; }
  .foo { color: green; }
`;

// …
```

In fact, the rendered CSS does not have a scoped body, anymore:

```css
/* Ractive.js component styles */

/* {c7d35506-0525-63f6-f618-e16cafaa8ccb} */

  @import url('https://fonts.googleapis.com/css?family=Shrikhand');
  body { background-color: red; }
  .foo[data-ractive-css~="{c7d35506-0525-63f6-f618-e16cafaa8ccb}"], [data-ractive-css~="{c7d35506-0525-63f6-f618-e16cafaa8ccb}"] .foo { color: green; } 
```

## Versions affected:

* 0.9.14 (my environment)
* 1.0.0-edge (playground)

## Platforms affected:

* Chromium 66.0.3359.181 on Ubuntu 16.04.4 LTS

## Reproduction:

→ [Playground](https://ractive.js.org/playground/?env=docs#N4IgFiBcoE5SBTAJgcwSAvgGhAF3gDxICWAbgATFIC8A5AIYAOjtAfAQPQmmsg4DO8AMYB7AHb9c5If37lq5AAYAdMeXIAjEUgCe5YJvpCA1ihgiArmKQBaUQBsRMSORjIA3OQyr1AOgBmIiL60iKOzuRmCAhint5iiu6qqqISUrgIALaM9vQZ8ko+5ERk0rmydIEibAASCPaOWOQA6k72SACEnNysqonJYqmS5ACCzAUASka4ZAi+CAAeGdYAFMDJuDL8WBsZ2bkZqhgAlEliqlNCM6QIaxui2eIxuPwuBmOMXjvnuLj0MGhcC5aABiJgsb7KX5ZHJ5BDAggfDisWhHU6qTBAA)

**Comment by p3k** [comment]
Btw. just noticed that something similar happens when there is a syntax error instead of `@import`, e.g.

```js
const css = `
  // CSS comments need to be enclosed in /* */
  .foo { color: green; }
`;
```

(In fact, I am currently trying to compile with LESS the CSS rendered by Ractive, and LESS allows simple line comments.)

Here is the rendered CSS output which looks pretty, um, interesting to say the least:

```css
/* Ractive.js component styles */

/* {e25f538e-07bc-cd9b-7825-014cb8d6d82f} */

  //  CSS  comments  need  to  be  enclosed  in 
   .foo[data-ractive-css~="{e25f538e-07bc-cd9b-7825-014cb8d6d82f}"], //  CSS  comments  need  to  be  enclosed  in 
   [data-ractive-css~="{e25f538e-07bc-cd9b-7825-014cb8d6d82f}"] .foo, //  CSS  comments  need  to  be  enclosed  in[data-ractive-css~="{e25f538e-07bc-cd9b-7825-014cb8d6d82f}"] 
   .foo, //  CSS  comments  need  to  be  enclosed  [data-ractive-css~="{e25f538e-07bc-cd9b-7825-014cb8d6d82f}"] in 
   .foo, //  CSS  comments  need  to  be  enclosed[data-ractive-css~="{e25f538e-07bc-cd9b-7825-014cb8d6d82f}"]  in 
   .foo, //  CSS  comments  need  to  be  [data-ractive-css~="{e25f538e-07bc-cd9b-7825-014cb8d6d82f}"] enclosed  in 
   .foo, //  CSS  comments  need  to  be[data-ractive-css~="{e25f538e-07bc-cd9b-7825-014cb8d6d82f}"]  enclosed  in 
   .foo, //  CSS  comments  need  to  [data-ractive-css~="{e25f538e-07bc-cd9b-7825-014cb8d6d82f}"] be  enclosed  in 
   .foo, //  CSS  comments  need  to[data-ractive-css~="{e25f538e-07bc-cd9b-7825-014cb8d6d82f}"]  be  enclosed  in 
   .foo, //  CSS  comments  need  [data-ractive-css~="{e25f538e-07bc-cd9b-7825-014cb8d6d82f}"] to  be  enclosed  in 
   .foo, //  CSS  comments  need[data-ractive-css~="{e25f538e-07bc-cd9b-7825-014cb8d6d82f}"]  to  be  enclosed  in 
   .foo, //  CSS  comments  [data-ractive-css~="{e25f538e-07bc-cd9b-7825-014cb8d6d82f}"] need  to  be  enclosed  in 
   .foo, //  CSS  comments[data-ractive-css~="{e25f538e-07bc-cd9b-7825-014cb8d6d82f}"]  need  to  be  enclosed  in 
   .foo, //  CSS  [data-ractive-css~="{e25f538e-07bc-cd9b-7825-014cb8d6d82f}"] comments  need  to  be  enclosed  in 
   .foo, //  CSS[data-ractive-css~="{e25f538e-07bc-cd9b-7825-014cb8d6d82f}"]  comments  need  to  be  enclosed  in 
   .foo, //  [data-ractive-css~="{e25f538e-07bc-cd9b-7825-014cb8d6d82f}"] CSS  comments  need  to  be  enclosed  in 
   .foo, //[data-ractive-css~="{e25f538e-07bc-cd9b-7825-014cb8d6d82f}"]  CSS  comments  need  to  be  enclosed  in 
   .foo, [data-ractive-css~="{e25f538e-07bc-cd9b-7825-014cb8d6d82f}"] //  CSS  comments  need  to  be  enclosed  in 
   .foo { color: green; }
```
