### ISSUE TITLE
Comments can break CSS encapsulation

### ISSUE THREAD

**Issue by Rich-Harris** [ractivejs/ractive#469]
Following on from #452. This CSS...

``` css
/*p {
  font-family: 'Comic Sans MS';
}*/

p {
  font-family: 'Baskerville';
}
```

...turns into this:

``` css
/*p[data-rvcguid="xyz"], [data-rvcguid="xyz"] /*p {
  font-family: 'Comic Sans MS';
}*/

p[data-rvcguid="xyz"], [data-rvcguid="xyz"] */

p {
  font-family: 'Baskerville';
}
```
